import { useState } from "react";
import { ToolLayout } from "../../components/ToolLayout";
import { Sparkles } from "lucide-react";

export function AiSummarizer() {
  const [text, setText] = useState("");
  const [length, setLength] = useState("medium");
  const [summarizing, setSummarizing] = useState(false);
  const [summary, setSummary] = useState("");

  const handleSummarize = () => {
    setSummarizing(true);
    // Simulate AI summarization
    setTimeout(() => {
      setSummary(
        "This is a concise summary of the provided text. In a real implementation, this would be generated by an AI model that analyzes the input text and extracts the key points, maintaining the essential information while reducing the overall length."
      );
      setSummarizing(false);
    }, 2000);
  };

  const wordCount = text.trim().split(/\s+/).filter((word) => word.length > 0).length;

  return (
    <ToolLayout
      title="AI Summarizer"
      description="Summarize long texts instantly with AI"
    >
      <div className="space-y-6">
        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <div className="space-y-4">
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="block text-sm font-medium text-gray-700">
                  Text to summarize
                </label>
                <span className="text-sm text-gray-500">{wordCount} words</span>
              </div>
              <textarea
                value={text}
                onChange={(e) => setText(e.target.value)}
                placeholder="Paste your article, document, or any long text here..."
                className="w-full h-64 p-4 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Summary Length
              </label>
              <select
                value={length}
                onChange={(e) => setLength(e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="short">Short (1-2 sentences)</option>
                <option value="medium">Medium (1 paragraph)</option>
                <option value="long">Long (multiple paragraphs)</option>
              </select>
            </div>

            <button
              onClick={handleSummarize}
              disabled={!text || summarizing}
              className="w-full px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              <Sparkles className="w-5 h-5" />
              {summarizing ? "Summarizing..." : "Summarize"}
            </button>
          </div>
        </div>

        {summary && (
          <div className="bg-white rounded-xl border border-gray-200 p-6">
            <h3 className="font-semibold text-gray-900 mb-4">Summary</h3>
            <div className="p-4 bg-blue-50 rounded-lg text-gray-900 leading-relaxed">
              {summary}
            </div>
            <div className="flex gap-3 mt-4">
              <button className="px-4 py-2 bg-blue-50 text-blue-700 rounded-lg hover:bg-blue-100 transition-colors">
                Copy Summary
              </button>
              <button
                onClick={handleSummarize}
                className="px-4 py-2 bg-blue-50 text-blue-700 rounded-lg hover:bg-blue-100 transition-colors"
              >
                Regenerate
              </button>
            </div>
          </div>
        )}

        <div className="bg-blue-50 rounded-xl p-6 border border-blue-100">
          <h3 className="font-semibold text-gray-900 mb-3">Best for</h3>
          <ul className="space-y-2 text-sm text-gray-700">
            <li className="flex items-start gap-2">
              <span className="text-blue-600 mt-1">•</span>
              <span>Long articles and blog posts</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-blue-600 mt-1">•</span>
              <span>Research papers and academic texts</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-blue-600 mt-1">•</span>
              <span>Meeting notes and transcripts</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-blue-600 mt-1">•</span>
              <span>Product descriptions and reviews</span>
            </li>
          </ul>
        </div>
      </div>
    </ToolLayout>
  );
}
